### ISSUE TITLE
Image/file uploading

### ISSUE THREAD

**Issue by dubcanada** [bertoost/Craft-FroalaEditor#1]
Hey

I made my own plugin a while ago and mine has image/file uploading using Craft. Here is how I did it

https://gist.github.com/dubcanada/266875598c6cd5ba0342b6f83094b1e3

Add a controller with the PHP as in the first file

And with the froala editor config object add the second file stuff.

And then include the craft.js file to add the other functionality.

And it works exactly like redactor natively works.

All that's left to do is links.

**Comment by bertoost** [comment]
Cool! Thanks for sharing this.
I definitely will try to implement this for my FE plugin for Craft. Really need to finish that one too :-)

**Comment by adrienne** [comment]
Hey @dubcanada - is your plugin available anywhere? I am really in need of an editor.

**Comment by bertoost** [comment]
I am working on implementing this because I need this too.
Currently facing issues with inserting images from the Craft modal and a crashing editor..

**Comment by dubcanada** [comment]
[froalaeditor.zip](https://github.com/bertoost/Craft-FroalaEditor/files/498972/froalaeditor.zip)

Here you go! It's not on github anywhere as the project was private.

**Comment by dubcanada** [comment]
Let me know when you guys get what you need, I'm going to delete the file. It has the froala editor assets in it.

**Comment by adrienne** [comment]
Thanks! Maybe @bertoost can use your assets code to fix the issue in this
one! (Entry linking would be cool but i don't need it for this project)

**Comment by bertoost** [comment]
I already do, that is causing the crash issue. Don't know yet why and where.. Just dont have the time I wish for this to finish it, but hopefully asap

**Comment by dubcanada** [comment]
Well make a branch and push your code I have another craft project soon I'll take a look.

Everyone download the file?

**Comment by adrienne** [comment]
I downloaded it, thanks!

**Comment by bertoost** [comment]
Hi all,

I have managed to get the custom button (not yet the right icon) firing the Craft Entry modal and it's even putting back the link into the editor.
Unfortunate I am not able yet to get the selected text replaced with the link. Of course the link then should be with the selected text.

Take a look at the JS script;
https://github.com/bertoost/Craft-FroalaEditor/blob/develop/resources/js/cp.js

Anyone feeling to help me a bit further, that would be much appreciated. Thanks in advance.

**Comment by bertoost** [comment]
I think the problem is that the selection is gone. Since I clicked on the element/entry to link, the selection is undone by default. I should remember the selected text, before firing the Craft Modal. Even for getting the selected text, this cannot be done because I already clicked on an element/entry to link.

Trying to eliminate this by defining the necessary variables before firing the modal.

**Comment by bertoost** [comment]
A new try ended up with the solution I wanted, see
https://github.com/bertoost/Craft-FroalaEditor/blob/develop/resources/js/cp.js
But as said before... I lost the selection when I click an entry from the modal window. Because the focus from the editor is now on the selected entry.
Don't know yet how to fix it.

**Comment by bertoost** [comment]
Wow! Fixed it with "this.selection.save()" before the modal is shown. Thanks to https://github.com/froala support!

**Comment by bertoost** [comment]
Done! Release v1.0.0 is there!
